version: 0.2
phases:
    install:
        runtime-versions:
            python: 3.7
        commands:
            - pip install --upgrade pip
            - pip install pysqlite3
            # #Install dependencies needed for running the static analysis
            - pip install -r requirements.txt
            #- yum install sqlite-3.8.11-1.fc21.x86_64.rpm

    pre_build:
        commands:
            - python --version
artifacts:
    files:
        - '**/*'
