# Generated by Django 4.1.4 on 2023-04-03 19:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('src', '0002_auto_20221213_1347'),
    ]

    operations = [
        migrations.CreateModel(
            name='patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Active', max_length=50)),
                ('phone', models.CharField(max_length=20)),
                ('otp', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('role_admin_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='src.role_admin')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='patient_appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d_date', models.DateField()),
                ('start_time', models.CharField(max_length=10)),
                ('end_time', models.CharField(max_length=10)),
                ('doctor_name', models.CharField(max_length=20)),
                ('staus', models.BooleanField(default=False)),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='src.patient')),
                ('role_admin_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='src.role_admin')),
            ],
        ),
        migrations.CreateModel(
            name='patient_profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=50, null=True)),
                ('about', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(default='default.jpeg', upload_to='images/')),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='src.patient')),
            ],
        ),
        migrations.RemoveField(
            model_name='employee_profile',
            name='employee_id',
        ),
        migrations.RemoveField(
            model_name='employee_salary',
            name='employee_id',
        ),
        migrations.RemoveField(
            model_name='employee_salary',
            name='role_admin_id',
        ),
        migrations.RemoveField(
            model_name='employee_shift',
            name='employee_id',
        ),
        migrations.RemoveField(
            model_name='employee_shift',
            name='role_admin_id',
        ),
        migrations.DeleteModel(
            name='employee',
        ),
        migrations.DeleteModel(
            name='employee_profile',
        ),
        migrations.DeleteModel(
            name='employee_salary',
        ),
        migrations.DeleteModel(
            name='employee_shift',
        ),
    ]
